### ISSUE TITLE
Ability to change `sub-menu`

### ISSUE THREAD

**Issue by samikeijonen** [10up/component-navigation#12]
**Is your feature request related to a problem? Please describe.**
I noticed there is hard coded `sub-menu` class used in the nav component. Could this be part of settings so it could be changed to something else.

This would enable changing `sub-menu` class to something else that fits better for chosen naming convention.

**Describe the solution you'd like**
`sub-menu` can be default but this could be overwritten via settings.

**Comment by timwright12** [comment]
@samikeijonen it's using the default wordpress menu output

**Comment by samikeijonen** [comment]
Yep, which I sometimes/often want to change. Or use the component outside of WP.

**Comment by nicholasio** [comment]
Closed in favor of https://github.com/10up/component-library/issues/33
