### ISSUE TITLE
readme updates

### ISSUE THREAD

**Issue by jeffpaul** [10up/component-navigation#18]
**Is your feature request related to a problem? Please describe.**
It's not obvious the level of support provided for this repo, so let's add some clarification.

**Describe the solution you'd like**
- [x] add support level section and badge
- [ ] add license file and badge

**Describe alternatives you've considered**
none.

**Comment by jeffpaul** [comment]
As there's no described license yet, I'll hold off on applying a license file and badge to this repo until a license is confirmed.

**Comment by jeffpaul** [comment]
@timwright12 looks like we're stating MIT, you ok with me adding that license file+badge to the repo?  See: https://github.com/10up/component-navigation/blob/c576c004f141fffcc43b5e4ecd2ba1f03eebc4e6/package.json#L18.

**Comment by timwright12** [comment]
Looks like this got added, closing out
