### ISSUE TITLE
Using separate mobile menu in WordPress?

### ISSUE THREAD

**Issue by scpete** [10up/component-navigation#25]
Not really an issue, but a question I have not been able to answer after much searching.  Is it possible to use a separate mobile menu with the navigation component in WordPress that triggers at a specific breakpoint?  Any guidance would be greatly appreciated.

**Comment by timwright12** [comment]
@scpete yeah, you would just use two instances, but in general we try pretty hard just to use a single menu to accomplish all variations. If not, you can run into accessibility issues if a certain menu item has focus during a screen resize. We also lean on this plugin to move items around the DOM as needed: https://github.com/timwright12/util.move it's saved us a lot of time
