### ISSUE TITLE
Change entry point from src/navigation.js to dist/navigation.js

### ISSUE THREAD

**Issue by asvinb** [10up/component-navigation#26]
**Is your feature request related to a problem? Please describe.**
The entry point of the component (main value in package.json) points to ES6 code (https://github.com/10up/component-navigation/blob/master/package.json#L6) resulting in including the node_modules/@10up when transpiling code like we did in the theme scaffold: https://github.com/10up/theme-scaffold/blob/master/config/webpack.common.js#L68

**Describe the solution you'd like**
The entry point to be dist/navigation.js instead of src/navigation.js

**Comment by ivankruchkoff** [comment]
Linked issue in downstream dependency https://github.com/10up/theme-scaffold/issues/183

**Comment by timwright12** [comment]
Hold off on this one

**Comment by nicholasio** [comment]
This has been addressed here: https://github.com/10up/component-library/pull/10
