### ISSUE TITLE
aria-expanded not updated when ESC is pressed

### ISSUE THREAD

**Issue by asvinb** [10up/component-navigation#34]
**Describe the bug**
When the ESC key is used to close the submenus, the aria-expanded attribute stays set to "true" instead of changing to "false". This currently works as expected when using the Enter key to close the submenus.

**To Reproduce**
1. Use the keyboard to navigate through the navigation component
2. Click on parent menu item to display the submenu
3. Press the "ESC" key to close the submenu
4. The aria-expanded attribute of the parent menu item stays set to "true" instead of changing to "false"

**Expected behavior**
Ensure that the aria-expanded attribute value is changed to "false" when the ESC key closes the submenus.

**Comment by nicholasio** [comment]
Closed in favor of https://github.com/10up/component-library/issues/31
