### ISSUE TITLE
Option for Top Menu Item with children to be a link as well

### ISSUE THREAD

**Issue by lizkaraffa** [10up/component-navigation#37]
This component is great when we have a placeholder title for the top menu item. However, it is frustrating when we need to be able to link to the top menu item as well. I.e. "About" list item with children items of "Our Work", "Press", "FAQ" where "About" is a page. If we want to visit the About page we'd have to make it as a duplicate child item.

Since we already have an svg icon, it would be great for a setting on this component to allow you to have the top menu items be linkable and only the svg icon trigger the menu events or to keep the menu as its currently built where clicking the top menu item triggers the menu events.

**Comment by nicholasio** [comment]
Closed in favor of https://github.com/10up/component-library/issues/30
